### ISSUE TITLE
I2S audio solved?

### ISSUE THREAD

**Issue by kroon040** [blakadder/tx-ultimate#1]
Hi,

Is in tasmota also the new i2s audio available?

In the ESPhome that I test , the speaker works now fine.

https://github.com/SmartHome-yourself/sonoff-tx-ultimate-for-esphome/discussions/4#discussioncomment-6497746

I prefer the tasmota version, so it should be nice that is also works fine in there

**Comment by blakadder** [comment]
![Screenshot_20230722-223206_Brave.png](https://github.com/blakadder/tx-ultimate/assets/5904370/296521e8-bcde-444b-b0f2-a5383e5c3ef3)

**Comment by kroon040** [comment]
In the template still says terrible sound

https://templates.blakadder.com/sonoff_T5-1C-86.html
